### ISSUE TITLE
Inconsistency when merging a route.yml fragment with two different profiles (commons, demo)

### ISSUE THREAD

**Issue by vmarzal** [eclipse-jkube/jkube#2758]
### Describe the bug

Problem merging a 'route.yml' common configuration with a environment one. The result is not displaying several annotations placed in the common file.

### Eclipse JKube version

1.16.1

### Component

OpenShift Maven Plugin

### Apache Maven version

other (please specify in additional context)

### Gradle version

None

### Steps to reproduce

I was trying to extract a common configuration from the **metadata.annotations** route.yml files of two environments. 

Common configuration:

```yml
metadata:
  annotations:
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-prod
```

1. I put that piece in the **/common/route.yml**:

```yml
metadata:
  annotations:
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-prod
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
```

2. And delete it from the environment files (example from de **/demo/route.yml**) getting simple fragments like these:

```yml
metadata:
  namespace: demo-namespace
spec:
  host: demo-namespace.apps.ocpdes.es
```

3. The profile activation is performed with the configuration provided and the directories exist in **src/main/jkube**.

```xml
<profile>
	<id>demo</id>
	<properties>
		<spring.profiles.active>demo</spring.profiles.active>
		<jkube.environment>common,demo</jkube.environment>
	</properties>
</profile>
```

With the command '**mvn oc:resource -Pdemo**' I get that merged route.yml file with no trace of my custom annotations.

```yml
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    jkube.eclipse.org/scm-url: ...
    jkube.eclipse.org/scm-tag: HEAD
    jkube.eclipse.org/git-commit: 22ec86b77b032234a5a4d9c70bbda3f2e5e910a0
    jkube.eclipse.org/git-url: ...
    app.openshift.io/vcs-ref:...
    app.openshift.io/vcs-uri: ...
    jkube.eclipse.org/git-branch: ....
  labels:
```

### Expected behavior

The expected behavior is a **route.yml** file with the common annotations (in addition to the opinionated defaults):

```yml
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    cert-manager.io/issuer-name: letsencrypt-prod
    cert-manager.io/issuer-kind: ClusterIssuer
    jkube.eclipse.org/scm-url: ...
    jkube.eclipse.org/scm-tag: HEAD
    ....
```

### Runtime

OpenShift

### Kubernetes API Server version

1.22.15

### Environment

Windows

### Additional context

Maven 3.9.4

**Comment by arsenalzp** [comment]
Any chance to work on this issue for me?

**Comment by rohanKanojia** [comment]
Umm, it's not decided yet how to approach this problem. But if you want to give it a try and propose something, feel free to go ahead.

**Comment by arsenalzp** [comment]
Could you please assign it to me?

**Comment by rohanKanojia** [comment]
@arsenalzp : Sorry, we don't have any bot running for these kind of project chores.

Thanks for showing interest in fixing this issue.

**Comment by rohanKanojia** [comment]
@arsenalzp : Hello, are you still working on this issue?

**Comment by arsenalzp** [comment]
Hello,
I have two more issues and PRs which are being reviewed right now. Let me manage with them then I proceed with this issue.

**Comment by arsenalzp** [comment]
Hello,
Some of my PRs were accepted so I'm ready to work for this issue!

**Comment by arsenalzp** [comment]
Oh, I spent a couple of hours to troubleshoot the issue.
The main question:  how should it work, what is the expectation?
Enreacher creates two resources based on fragments were given, requester of issue used two files for the same resource/profile.
Name should be different based on environment names:
`common/common-route.yml` and `demo/demo-route.yml` for `common` and `demo` environments respectively, then two different files are produced:

`target/classes/META-INF/jkube/openshift/common-route.yml`:
```
apiVersion: v1
kind: Route
metadata:
  annotations:
    cert-manager.io/issuer-name: letsencrypt-prod
    cert-manager.io/issuer-kind: ClusterIssuer
  labels:
    testProject: spring-boot-sample
    app: spring-boot
    provider: jkube
    version: 1.17.0
    group: org.eclipse.jkube.quickstarts.maven
    app.kubernetes.io/part-of: org.eclipse.jkube.quickstarts.maven
    app.kubernetes.io/managed-by: jkube
    app.kubernetes.io/name: spring-boot
    app.kubernetes.io/version: 1.17.0
  name: common
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
```

and 

`target/classes/META-INF/jkube/openshift/demo-route.yml`:
```
apiVersion: v1
kind: Route
metadata:
  labels:
    testProject: spring-boot-sample
    app: spring-boot
    provider: jkube
    version: 1.17.0
    group: org.eclipse.jkube.quickstarts.maven
    app.kubernetes.io/part-of: org.eclipse.jkube.quickstarts.maven
    app.kubernetes.io/managed-by: jkube
    app.kubernetes.io/name: spring-boot
    app.kubernetes.io/version: 1.17.0
  name: demo
  namespace: demo-namespace
spec:
  host: demo-namespace.apps.ocpdes.es
```
