### ISSUE TITLE
TriggersAnnotationEnricher generates wrong `image.openshift.io/triggers` annotation on windows

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#3591]
### Describe the bug

Related to https://github.com/eclipse-jkube/jkube/issues/3477

When I'm trying to generate `image.openshift.io/triggers` annotation using TriggersAnnotationEnricher, I'm getting a malformed annotation with platform specific line breaks.

This is the configuration I'm using for OpenShift Maven Plugin:
```xml
			<configuration>
			   <enricher>
			      <config>
			         <jkube-triggers-annotation>
                                     <containers>quarkus</containers>
                                  </jkube-triggers-annotation>
			      </config>
			    </enricher>
	                 </configuration>
```

However, this generates annotation like this on windows:
```yaml
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      jkube.eclipse.org/git-branch: main
      image.openshift.io/triggers: "[ {\r\n  \"from\" : {\r\n    \"kind\" : \"ImageStreamTag\"\
        ,\r\n    \"name\" : \"jkube-triggers-annotation-demo:latest\"\r\n  },\r\n\
        \  \"fieldPath\" : \"spec.template.spec.containers[?(@.name==\\\"quarkus\\\
        \")].image\"\r\n} ]"
```

### Eclipse JKube version

1.17.0

### Component

OpenShift Maven Plugin

### Apache Maven version

other (please specify in additional context)

### Gradle version

None

### Steps to reproduce

1. Add configuration as described in issue description
2. Run `oc:resource`
3. Inspect `target/classes/META-INF/jkube/openshift.yml` for `image.openshift.io/triggers` annotation

### Expected behavior

Generated `openshift.yml` should not have windows line breaks in annotation

### Runtime

OpenShift

### Kubernetes API Server version

1.25.3

### Environment

Windows

### Sample Reproducer Project

[jkube-triggers-annotation-demo-reproducer.zip](https://github.com/user-attachments/files/18165711/jkube-triggers-annotation-demo-reproducer.zip)

### Additional context

Apache Maven Version : 3.9.9
